#ifndef ID_HPP
#define ID_HPP

enum
{
    ID_ATTR0 = 1,
    ID_ATTR1,
    ID_ATTR2,
    ID_ATTR3,
    ID_COLLISION,
    ID_LAYER0,
    ID_LAYER1,
    ID_ZOOM_100,
    ID_ZOOM_200,
    ID_ZOOM_400,
    ID_ZOOM_800,
    ID_ZOOM_1600,
    ID_R_NEW_PAGE,
    ID_R_DELETE_PAGE,
    ID_R_CLONE_PAGE,
    ID_R_RENAME_PAGE,
    ID_R_MANAGE_TABS,
    ID_R_CLOSE_TAB,
    ID_FILL,
    ID_FILL_PASTE,
    ID_FILL_ATTRIBUTE,
    ID_TOOL_STAMP,
    ID_TOOL_DROPPER,
    ID_TOOL_SELECT,
    ID_DELETE_OBJ,
    ID_MANAGE_TABS,
    ID_SHOW_COLLISIONS,
    ID_LEVEL_GRID,
    ID_SELECT_ALL,
    ID_SELECT_NONE,
    ID_SELECT_USAGE,
    ID_SELECT_INVERT,
};

#endif
